# Chapter 13.3.3 Keras Preprocessing Layers

##### Normalization Layer

In [1]:
import numpy as np
import tensorflow as tf

data = np.arange(12).reshape(4, 3)

normalization = tf.keras.layers.Normalization()
normalization.adapt(data)
print(data)
print(normalization(data))

2022-10-22 22:12:36.911114: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
tf.Tensor(
[[-1.3416408 -1.3416408 -1.3416408]
 [-0.4472136 -0.4472136 -0.4472136]
 [ 0.4472136  0.4472136  0.4472136]
 [ 1.3416408  1.3416408  1.3416408]], shape=(4, 3), dtype=float32)


2022-10-22 22:12:38.828066: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-22 22:12:38.894030: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-22 22:12:38.894419: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-22 22:12:38.894987: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropri

##### Discretization Layer

In [2]:
data = np.arange(18).reshape(6, 3)

discretization = tf.keras.layers.Discretization(num_bins=3)
discretization.adapt(data)
discretization(data)

<tf.Tensor: shape=(6, 3), dtype=int64, numpy=
array([[0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 2],
       [2, 2, 2],
       [2, 2, 2]])>

##### TextVectorization Layer

In [3]:
data = [
    "The greatest glory lies in rising every time we fall.",
    "The way to get started is to quit talking and begin doing.",
    "Don't waste it living someone else's life.",
    "If life were predictable it would lose flavor",
    "The way we see the life",
]

text_vectorization = tf.keras.layers.TextVectorization()
text_vectorization.adapt(data)
text_vectorization(data)

<tf.Tensor: shape=(5, 12), dtype=int64, numpy=
array([[ 2, 25, 26, 21, 23, 16, 30, 11,  4, 29,  0,  0],
       [ 2,  5,  6, 27, 13, 22,  6, 17, 12, 35, 34, 33],
       [32, 10,  7, 20, 14, 31,  3,  0,  0,  0,  0,  0],
       [24,  3,  9, 18,  7,  8, 19, 28,  0,  0,  0,  0],
       [ 2,  5,  4, 15,  2,  3,  0,  0,  0,  0,  0,  0]])>

In [4]:
text_vectorization = tf.keras.layers.TextVectorization(output_mode="multi_hot")
text_vectorization.adapt(data)
text_vectorization(data)

<tf.Tensor: shape=(5, 35), dtype=float32, numpy=
array([[0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0.,
        0., 0., 0.],
       [0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
        1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        1., 1., 1.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
        0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]], dtype=float32)>

In [5]:
text_vectorization = tf.keras.layers.TextVectorization(output_mode="count")
text_vectorization.adapt(data)
text_vectorization(data)

<tf.Tensor: shape=(5, 35), dtype=float32, numpy=
array([[0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0.,
        0., 0., 0.],
       [0., 1., 0., 0., 1., 2., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
        1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        1., 1., 1.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
        0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 2., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]], dtype=float32)>

In [6]:
text_vectorization = tf.keras.layers.TextVectorization(output_mode="tf_idf")
text_vectorization.adapt(data)
text_vectorization(data)

<tf.Tensor: shape=(5, 35), dtype=float32, numpy=
array([[0.        , 0.8109302 , 0.        , 0.98082924, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.2527629 , 0.        , 0.        , 0.        , 0.        ,
        1.2527629 , 0.        , 0.        , 0.        , 0.        ,
        1.2527629 , 0.        , 1.2527629 , 0.        , 1.2527629 ,
        1.2527629 , 0.        , 0.        , 1.2527629 , 1.2527629 ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.8109302 , 0.        , 0.        , 0.98082924,
        2.5055258 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.2527629 , 1.2527629 , 0.        , 0.        ,
        0.        , 1.2527629 , 0.        , 0.        , 0.        ,
        0.        , 1.2527629 , 0.        , 0.        , 0.        ,
        0.        , 1.2527629 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.2527629 , 1.2527629 , 1.2527629 

##### How TensorFlow / Keras Calculates TF-IDF

In [7]:
# Term counts
terms = ["the", "way", "we", "see", "lift"]

# Term frequency
tf = np.array([2, 1, 1, 1, 1])

# Number of documents
D = 5

# Number of documents containing the term
d = np.array([3, 2, 2, 1, 3])

# Inverse document frequency
idf = np.log(1 + D / (d + 1))

# tf-idf
tf * idf

array([1.62186043, 0.98082925, 0.98082925, 1.25276297, 0.81093022])