# Section 1: Using TensorFlow like NumPy

In [94]:
import numpy as np
import tensorflow as tf

## 1.1 Tensors and Operations

Scaler

In [95]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

Matrix

In [96]:
t = tf.constant([[1., 2, 3], [4, 5, 6]])
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

Shape and data type

In [97]:
t.shape

TensorShape([2, 3])

In [98]:
t.dtype

tf.float32

Indexing

In [99]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [100]:
t[..., 1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

In [101]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [102]:
t[..., tf.newaxis, 1]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [103]:
t[tf.newaxis, ..., 1]

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[2., 5.]], dtype=float32)>

In [104]:
t[..., 1, tf.newaxis, tf.newaxis]

<tf.Tensor: shape=(2, 1, 1), dtype=float32, numpy=
array([[[2.]],

       [[5.]]], dtype=float32)>

Tensor operations

In [105]:
t * t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [106]:
t_t = tf.transpose(t)
t_t

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [107]:
t @ t_t

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [108]:
m = np.arange(1, 7).reshape(2, 3)
m

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
m @ m.T

array([[14, 32],
       [32, 77]])

In [110]:
a = [[1, 2, 3], [4, 5, 6]]
a

[[1, 2, 3], [4, 5, 6]]

In [111]:
b = list(zip(*a))
b

[(1, 4), (2, 5), (3, 6)]

In [112]:
# Error unsupported operand type
# a @ b

Math operations

In [113]:
tf.reduce_mean(t)

<tf.Tensor: shape=(), dtype=float32, numpy=3.5>

Keras' low-level API

In [114]:
import tensorflow.keras.backend as K

K.square(K.transpose(t))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1., 16.],
       [ 4., 25.],
       [ 9., 36.]], dtype=float32)>

## 1.2 Tensors and NumPy

In [115]:
a = np.arange(3, dtype=float)
a

array([0., 1., 2.])

In [116]:
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0., 1., 2.])>

In [117]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [118]:
np.asarray(t)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [119]:
a = np.arange(3, dtype="float32")
a.dtype

dtype('float32')

In [120]:
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 1., 2.], dtype=float32)>

## 1.3 Type Conversions

In [121]:
# tf.constant(2.) + tf.constant(42)

In [122]:
# tf.constant(2.) + tf.constant(42., dtype=tf.float64)

In [123]:
tf.constant(2.) + tf.cast(tf.constant(42., dtype=tf.float64), tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=44.0>

## 1.4 Variables

In [124]:
v = tf.Variable([[1, 2, 3], [4, 5, 6]], dtype=float)
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [125]:
w = 2 * v
w

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [126]:
v.assign(2 * v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [128]:
v[0, 1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [130]:
v[:, 2].assign([100, 200])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  2.,  42., 100.],
       [  8.,  10., 200.]], dtype=float32)>

In [131]:
v.scatter_nd_update(indices=[[0, 0], [1, 2]], updates=[0.1, 0.2])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  0.1,  42. , 100. ],
       [  8. ,  10. ,   0.2]], dtype=float32)>

## 1.5 Other Data Structures