# Tensorflow Functions and Graphs

### Introduction

In [1]:
import tensorflow as tf

tf_square = tf.function(lambda x: x**2)
tf_square

In [2]:
tf_square(2.0)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [4]:
@tf.function
def tf_square(x):
    return x**2


tf_square

In [6]:
tf_square(3.0)

<tf.Tensor: shape=(), dtype=float32, numpy=9.0>

In [8]:
import numpy as np

print(np.shape(3))
print(np.shape([3]))

()
(1,)


In [9]:
tf.autograph.to_code(tf_square.python_function)

"def tf__tf_square(x):\n    with ag__.FunctionScope('tf_square', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:\n        do_return = False\n        retval_ = ag__.UndefinedReturnValue()\n        try:\n            do_return = True\n            retval_ = (ag__.ld(x) ** 2)\n        except:\n            do_return = False\n            raise\n        return fscope.ret(retval_, do_return)\n"

In [11]:
@tf.function
def random_num(x):
    return np.random.rand()


print(random_num(1))
print(random_num(2))
print(random_num(tf.constant(1)))
print(random_num(tf.constant(2)))

tf.Tensor(0.20521198, shape=(), dtype=float32)
tf.Tensor(0.9065957, shape=(), dtype=float32)
tf.Tensor(0.9017117, shape=(), dtype=float32)
tf.Tensor(0.9017117, shape=(), dtype=float32)


In [13]:
@tf.function
def random_num(x):
    return tf.random.uniform([])


print(random_num(1))
print(random_num(2))
print(random_num(tf.constant(1)))
print(random_num(tf.constant(2)))

tf.Tensor(0.12950444, shape=(), dtype=float32)
tf.Tensor(0.27884734, shape=(), dtype=float32)
tf.Tensor(0.30035996, shape=(), dtype=float32)
tf.Tensor(0.43550706, shape=(), dtype=float32)


### TF Functions and Concrete Functions

In [15]:
concrete_function = tf_square.get_concrete_function(tf.constant([2.0, 3]))
concrete_function

<ConcreteFunction tf_square(x) at 0x7FB2803261F0>

In [18]:
concrete_function(tf.constant([4.0, 5]))

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([16., 25.], dtype=float32)>